### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character with urls that contain html entities

### ISSUE THREAD

**Issue by fxbonnet** [esigate/esigate#125]
When rewriting an url, html entities are not unescaped. If the url contains several numeric entities like &#39; it is considered as an invalid url because # character is reserved for fragments. So it causes the following stack trace:
```
java.lang.IllegalArgumentException: Illegal character in fragment at index 39: http://backend?param=I&#39;am&param2=I&#39;am
	at java.net.URI.create(URI.java:859)
	at org.esigate.util.UriUtils.createURI(UriUtils.java:189)
	at org.esigate.util.UriUtils.resolve(UriUtils.java:345)
	at org.esigate.impl.UrlRewriter.rewriteUrl(UrlRewriter.java:156)
	at org.esigate.impl.UrlRewriter.rewriteHtml(UrlRewriter.java:225)
	...
```
The solution is to unescape entities before rewriting and to escape again after.

**Comment by fxbonnet** [comment]
Fixed
