### ISSUE TITLE
Nested Choose/when/otherwise tags

### ISSUE THREAD

**Issue by StevenWeathers** [esigate/esigate#152]
Having issues with Nested Choose/When/Otherwise Tags here's the example and the error received.

```
<esi:choose>
    <esi:when test="$exists($(HTTP_COOKIE{'FIRST_COOKIE'}))">
       <esi:choose>
          <esi:when test="$exists($(HTTP_COOKIE{'SECOND_COOKIE'}))">
               HAS SECOND COOKIE
          </esi:when>
            <esi:otherwise>
                NO SECOND COOKIE
            </esi:otherwise>
        </esi:choose>
    </esi:when>
    <esi:otherwise>
        NO FIRST COOKIE
    </esi:otherwise>
</esi:choose>
````

```
java.lang.NullPointerException
	at org.esigate.esi.BaseElement.characters(BaseElement.java:54)
	at org.esigate.parser.ParserContextImpl.characters(ParserContextImpl.java:107)
	at org.esigate.parser.Parser.parse(Parser.java:71)
	at org.esigate.esi.EsiRenderer.render(EsiRenderer.java:122)
	at org.esigate.Driver.performRendering(Driver.java:402)
	at org.esigate.Driver.performRendering(Driver.java:361)
	at org.esigate.Driver.proxy(Driver.java:296)
	at org.esigate.DriverFactory.proxy(DriverFactory.java:403)
	at org.esigate.servlet.ProxyFilter.doFilter(ProxyFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1624)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1112)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:479)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1046)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:459)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:281)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:745)
```

Thoughts?

**Comment by fxbonnet** [comment]
Probably a bug in the ESI parser. I have been able to reproduce it in a unit test. Trying to find a fix

**Comment by fxbonnet** [comment]
I just pushed a fix. Could you check that it works for you? (You can use the latest snapshot on https://oss.sonatype.org/content/repositories/snapshots)

**Comment by StevenWeathers** [comment]
Validated works thanks!
