### ISSUE TITLE
NPE in tomcat logs

### ISSUE THREAD

**Issue by nricheton** [esigate/esigate#181]
A NPE can sometime happen in tomcat logs : 

05-Mar-2018 08:57:13.466 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke "Servlet.service()" pour la servlet default a généré une exception
java.lang.NullPointerException
at org.esigate.http.cookie.CookieUtil.encodeCookie(CookieUtil.java:51)
at org.esigate.servlet.impl.ResponseSender.sendHeaders(ResponseSender.java:64)
at org.esigate.servlet.impl.ResponseSender.sendResponse(ResponseSender.java:42)
at org.esigate.servlet.ProxyFilter.doFilter(ProxyFilter.java:61)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1580)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1537)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)

**Comment by nricheton** [comment]
Should be fixed in master. However, I was not able to reproduce in a unit test.

**Comment by fxbonnet** [comment]
Closed the issue. We will reopen it if the exception comes back
